

Installing and loading packages.
```{r packages}
#### Packages ####
## If a package is installed, it will be loaded. If any 
## are not, the missing package(s) will be installed 
## from CRAN and then loaded.

## Packages of interest
packages = c("tidyverse", "tigris", "sf", "viridis", "lubridate")

## Now load or install&load all
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE)
      library(x, character.only = TRUE)}})
```


Loading in the data.
```{r}

raw_data <- read.csv("data/homicide-data.csv")

balt <- raw_data %>% filter(city == "Baltimore") %>% mutate(
  reported_date = ymd(reported_date),
  year_month = format(reported_date , "%Y-%m"), 
  month = as.numeric(format(reported_date , "%m")), 
  season = if_else(between(month, 05, 10), "Summer", "Winter")
)

balt2 <- balt %>% group_by(year_month, season) %>% 
  summarize(
    homicide = n()
  ) %>% mutate(
    year_month = as.Date(ym(year_month))
  )

freddie <- balt %>% filter( victim_first =="FREDDIE CARLOS") %>% mutate(
    year_month = as.Date(ym(year_month))
  )

```


```{r}
pal <- c(
  "Summer" = "light grey",
  "Winter" = "light blue"
)

ggplot(data = balt2, aes(x = year_month, y = homicide)) +
  geom_col(aes(fill = season)) + 
  scale_fill_manual(
    values = pal,
    limits = names(pal)
  ) +
  geom_smooth() + ## need to fix
  scale_x_date(date_labels = "%Y") + 
  labs(
    title = "Homicides in Baltimore, MD", 
    y = "Monthly homicides",
    x = "Date"
  ) + 
  theme_dark() + 
  theme(legend.position="bottom", legend.title= element_blank()) + 
  geom_vline(xintercept= freddie$year_month, linetype="dashed", color = "red", size = 2) + 
  geom_text(label = "Arrest of", x = freddie$year_month - 250, y = 45, color = "white")+
  geom_text(label = "Freddie Gray", x = freddie$year_month - 330, y = 41, color = "white")



```